on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 14.x
        
    - name: install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/ADFroot/build
        

    - name: Validate
      run: npm run build validate ${{github.workspace}}/ADFroot/ /subscriptions/41ae3075-2ae0-4d8a-8233-c602b5f8ef28/resourceGroups/adf-source-rg/providers/Microsoft.DataFactory/factories/adf-source 
      working-directory: ${{github.workspace}}/ADFroot/build
 

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/ADFroot/ /subscriptions/41ae3075-2ae0-4d8a-8233-c602b5f8ef28/resourceGroups/adf-source-rg/providers/Microsoft.DataFactory/factories/adf-source "ExportedArmTemplate" 
      working-directory: ${{github.workspace}}/ADFroot/build
 

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ExportedArmTemplate
        path: ${{github.workspace}}/ADFroot/build/ExportedArmTemplate
        
  release:
    needs: build
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ExportedArmTemplate # (5) Artifact name 


      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: adf-destination-rg
          dataFactoryName: adf-destination
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          additionalParameters: factoryName=adf-destination

  
      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: adf-destination-rg
          dataFactoryName: adf-destination-2
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          additionalParameters: factoryName=adf-destination-2 
      
    
  
